# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.12' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install pipx
        run: python -m pip install --upgrade pip pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: Show Poetry version
        run: poetry --version

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Lint
        run: poetry run ruff check .

      - name: Tests
        run: poetry run pytest -q
